Sky:
    CMB: 
        cmb: True
        seed: 1
        r: 0
        Alens: 0.5
    Foregrounds:
        dust: True
        dustmodel: 'd0'
        sync: True
        syncmodel: 's0'

    nside: 64

Spectrum:
    lmin: 30
    lmax: 100
    dl: 15

noise: True

UWBTube1:
    add: False
    nrec: 1
    central_nu: 130
    bw: 80
    raw_depth: 1

UWBTube2:
    add: False
    nrec: 5
    central_nu: 240
    bw: 80
    raw_depth: 1

filename: 'mytest'
foldername: 'test'